version: '3.6'

services:

  vault:
    build:
      context: ./docker/vault
      dockerfile: Dockerfile
    ports:
      - 8200:8200
    volumes:
      - ./docker/vault/config:/vault/config
      - ./docker/vault/policies:/vault/policies
      - ./docker/vault/data:/vault/data
      - ./docker/vault/logs:/vault/logs
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    command: server -config=/vault/config/vault-config.json
    cap_add:
      - IPC_LOCK
    depends_on:
      - consul

  consul:
    build:
      context: ./docker/consul
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 1 -config-file=/consul/config/config.json
    volumes:
      - ./docker/consul/config/consul-config.json:/consul/config/config.json
      - ./docker/consul/data:/consul/data
  consul-worker:
    build:
      context: ./docker/consul
      dockerfile: Dockerfile
    command: agent -server -join consul -config-file=/consul/config/config.json
    volumes:
      - ./docker/consul/config/consul-config.json:/consul/config/config.json
    depends_on:
      - consul